name: AdditionalEnchantments
version: 1.0.0-alpha-1
main: eu.m0dex.additionalenchantments.AdditionalEnchantments
author: M0dEx
commands:
    additionalenchantments:
        description: Main command.
        usage: /ae
        aliases: ae