enchantments:
    common:
        cowardice:
            max-level: 3
            cooldown: 15
            speed-level: 2
            base-chance: 10
            chance-increase: 5
            base-duration: 2
            duration-increase: 1
        frost:
            max-level: 3
            slowness-level: 2
            base-chance: 10
            chance-increase: 5
            base-duration: 2
            duration-increase: 1
        marksman:
            max-level: 3
            speed-level: 2
            base-chance: 25
            chance-increase: 5
            base-duration: 2
            duration-increase: 1
    uncommon:
        block:
            max-level: 3
            base-chance: 5
            chance-increase: 2.5
        frost-armor:
            max-level: 3
            weakness-level: 1
            base-chance: 5
            chance-increase: 2.5
    rare:
        berserk:
            max-level: 5
            base-scaling: 1
            scaling-increase: 0.125
        lifesteal:
            max-level: 3
            base-percentage: 20
            percentage-increase: 10
        perfect-forge:
            max-level: 5
            base-reduction: 20
            reduction-increase: 15
    legendary:
        deathbringer:
            max-level: 1
            damage-multiplier: 2
            base-chance: 25
            chance-increase: 0
        blessing:
            max-level: 3
            base-heal: 2
            heal-increase: 1.5
            base-chance: 5
            chance-increase: 2.5
        overload:
            max-level: 5
            base-hp: 2
            hp-increase: 2
    godly:
        planetary-deathbringer:
            max-level: 1
            damage-multiplier: 2.5
            base-chance: 25